# Generated by Django 3.2.6 on 2021-08-14 23:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
            options={
                'verbose_name': '社員',
                'verbose_name_plural': '社員',
            },
        ),
        migrations.CreateModel(
            name='MynumberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='マイナンバー')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.employee', verbose_name='社員名')),
            ],
            options={
                'verbose_name': 'マイナンバー',
                'verbose_name_plural': 'マイナンバー',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('address', models.CharField(max_length=250, verbose_name='住所')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.employee', verbose_name='社員名')),
            ],
            options={
                'verbose_name': '連絡先',
                'verbose_name_plural': '連絡先',
            },
        ),
    ]
