# Generated by Django 3.2.6 on 2021-08-15 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="携帯の電話番号を入力してください。 例：'09012345678'", regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
