# Generated by Django 3.2.6 on 2021-08-15 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contact_info', to='app.employee', verbose_name='社員名'),
        ),
        migrations.AlterField(
            model_name='mynumbercard',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mynumber', to='app.employee', verbose_name='社員名'),
        ),
    ]
